name: crux
description: A rock climbing training app.

version: 1.0.0+1

# Caret syntax provides a more compact way of expressing the most common sort of version constraint.
# ^version means “the range of all versions guaranteed to be backwards compatible with the specified version”,
# and follows pub’s convention for semantic versioning. For example, ^1.2.3 is equivalent to '>=1.2.3 <2.0.0',
# and ^0.1.2 is equivalent to '>=0.1.2 <0.2.0'.
# i.e. up to the next breaking version
environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ^1.14.6

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  cupertino_icons: ^0.1.2

  bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  rxdart: ^0.22.0
  equatable: ^0.6.0

dev_dependencies:
  test: ^1.9.0
  test_api: ^0.2.11
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/gym_climber_crimping.jpg
    - assets/images/google_logo.png
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-ExtraBold.otf
